### ISSUE TITLE
Another data synthesis tool in R

### ISSUE THREAD

**Issue by thomvolker** [UtrechtUniversity/privacy-engineering-tools#3]
Hi all,

I stumbled upon this and think it is a great initiative. I am writing to let you know that not so long ago, @gerkovink and I wrote a paper on how one can use the R package `mice` to create synthetic data in `R` (see https://www.mdpi.com/2624-8611/3/4/45). I think it would be a good contribution to the list of tools. 

Please let me know if I should use another means of communication, because an issue might not be the most suitable way of doing this.

All the best,
Thom

**Comment by qubixes** [comment]
Hi Thom,

Thanks for your suggestion! An issue is a great way to notify us of new packages! If you want you can do a pull request of the package, since you're probably better equipped than us to write a nice one-liner description in the context of synthetic data. Otherwise, let me know and I can make one myself.

**Comment by DorienHuijser** [comment]
Haha, I thought this issue would automatically close when merging Thom's PR but apparently not, doing it manually then.
Thanks again Thom!
