### ISSUE TITLE
More python packages synthetic data - are these suitable to add?

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/privacy-engineering-tools#5]
Hello! I've found some more python packages for creating synthetic data. As I'm not sure what the quality is, I'm adding them here and leaving @qubixes to decide if they should be added or not :)

Found on https://www.activestate.com/blog/top-10-python-packages-for-creating-synthetic-data/:
- SymPy (increasing data points)
- Mesa (complex scenarios)
- Zpy (Image data)
- Blender (Image and video data)

And a package to check the performance of a synthetic dataset (whatever that means): https://github.com/mostly-ai/virtualdatalab

**Comment by qubixes** [comment]
SymPy: This seems to general to me for the list, you can make synthetic data with it, but so can you with Numpy.
Mesa: Agent based modelling. Again can be used for synthetic data. I decided to keep most of the simulation packages out of the tools list, because they are not necessarily aimed at privacy, but this can be changed of course.
Zpy: This may be interesting to put in the list. It is quite specific, and very geared towards ML applications.
Blender: Too general of a package I think, can render anything for any reason.

**Comment by DorienHuijser** [comment]
Thanks Raoul! Closing this issue :)
